<a href="https://colab.research.google.com/github/pran-pixel/NASSCOM1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
# 🔹 1. ARRAY CREATION FUNCTION
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)



Array using arange: [0 2 4 6 8]


In [41]:
arr2= np.linspace(0,1,5)
print("array using linspace",arr2)

array using linspace [0.   0.25 0.5  0.75 1.  ]


In [42]:
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [43]:
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [44]:
data = np.array([[5, 8, 9], [2, 4, 6]])
print("Original Data:\n", data)


Original Data:
 [[5 8 9]
 [2 4 6]]


In [45]:
print("Sum of all elements", np.sum(data))             # Total sum
print("Column-wise sum", np.sum(data, axis=0))         # Sum along columns
print("Row-wise mean", np.mean(data, axis=1))          # Average of each row
print("Max value", np.max(data))                       # Maximum value



Sum of all elements 34
Column-wise sum [ 7 12 15]
Row-wise mean [7.33333333 4.        ]
Max value 9


In [46]:
print("min of data:",np.min(data))
print("index of max value(flattened)",np.argmax(data))
print("standard deviation:",np.std(data))

min of data: 2
index of max value(flattened) 2
standard deviation: 2.3570226039551585


In [47]:
a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)

# Find indices where condition is True (value > 4)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Original Array: [3 1 7 2 9]
Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]


In [48]:
A = np.array([[1, 2], [3, 4]])  # 2x2 matrix
B = np.array([10, 20])          # 1D array with 2 elements

print("Matrix A:\n", A)
print("Vector B:", B)
C=A+B
print("Matrix A+B:\n",C)

Matrix A:
 [[1 2]
 [3 4]]
Vector B: [10 20]
Matrix A+B:
 [[11 22]
 [13 24]]


In [49]:
nums = np.array([1, 2, 3, 4, 5])
print("Original Array:", nums)
mask = nums > 3
print("Mask (nums > 3):", mask)


Original Array: [1 2 3 4 5]
Mask (nums > 3): [False False False  True  True]


In [50]:
filtered = nums[mask]
print("Filtered values:", filtered)
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)


Filtered values: [4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [51]:

arr_orig = np.array([10, 20, 30])
arr_view = arr_orig[:]
arr_view[0] = 99
print("Original After View Change:", arr_orig)

Original After View Change: [99 20 30]


In [52]:
arr_copy = arr_orig.copy()
arr_copy[0] = 55
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)


Original After Copy Change: [99 20 30]
Copy: [55 20 30]


In [53]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [54]:
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)

Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [55]:
# Random integers from 0 to 100 in 3x3 matrix
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random values from standard normal distribution (mean=0, std=1)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)

Random Integers:
 [[88 18  7]
 [ 6 41 67]
 [ 1 97 64]]
Random Normal Distribution:
 [[ 0.47350253  1.80845293 -1.54128759 -1.12341786]
 [ 0.04014183  1.26107594  0.51278771 -0.6194785 ]]


In [56]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)

# Access single elements by index
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])


Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [57]:
print("Slice from index 1 to 4:", arr[1:4])
# Slice with step
print("Every second element:", arr[::2])
# Reverse array
print("Reversed array:", arr[::-1])


Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [58]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:\n", matrix[:2, :2])



Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [62]:
arr = np.array([5, 10, 15, 20, 25, 30])

# Create a boolean mask for values > 15
mask = arr > 15
print("Boolean Mask:", mask)

# Use mask to filter elements
print("Values greater than 15:", arr[mask])

# Combine conditions
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])

Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]
